"""initial_migration

Revision ID: c2c155e74fc3
Revises: None
Create Date: 2026-06-05 17:35:10.582449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c155e74fc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('CRITICA', 'ADVERTENCIA', 'INFORMATIVA', 'MOTIVACIONAL', name='tipoalerta'), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_leida'), 'alerts', ['leida'], unique=False)
    op.create_index(op.f('ix_alerts_tipo'), 'alerts', ['tipo'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('monto_base', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('ingresos_adicionales', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('total_gastado', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('saldo_disponible', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.CheckConstraint('ingresos_adicionales >= 0', name='check_budget_ingresos_adicionales_positivo'),
    sa.CheckConstraint('monto_base >= 0', name='check_budget_monto_base_positivo'),
    sa.CheckConstraint('total_gastado >= 0', name='check_budget_total_gastado_positivo'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mes', 'anio', name='uq_user_budget_mes_anio')
    )
    op.create_index(op.f('ix_budgets_anio'), 'budgets', ['anio'], unique=False)
    op.create_index(op.f('ix_budgets_mes'), 'budgets', ['mes'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Enum('COMIDA', 'TRANSPORTE', 'OCIO', 'SALUD', 'EDUCACION', 'ROPA', 'HOGAR', 'TECNOLOGIA', 'VIAJES', 'OTROS', name='categoriagasto'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('comercio', sa.String(length=150), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fuente', sa.Enum('MANUAL', 'OCR_IMAGEN', 'OCR_PDF', name='fuentegasto'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('monto > 0', name='check_expense_monto_positivo'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_categoria'), 'expenses', ['categoria'], unique=False)
    op.create_index(op.f('ix_expenses_fecha'), 'expenses', ['fecha'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('monto_objetivo', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('saldo_acumulado', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', 'CANCELADA', name='estadometa'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('monto_objetivo > 0', name='check_goal_monto_objetivo_positivo'),
    sa.CheckConstraint('saldo_acumulado >= 0', name='check_goal_saldo_acumulado_positivo'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_estado'), 'goals', ['estado'], unique=False)
    op.create_table('smart_score_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('fecha_calculo', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='check_score_rango_valido'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mes', 'anio', name='uq_user_score_mes_anio')
    )
    op.create_index(op.f('ix_smart_score_history_anio'), 'smart_score_history', ['anio'], unique=False)
    op.create_index(op.f('ix_smart_score_history_mes'), 'smart_score_history', ['mes'], unique=False)
    op.create_table('income_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('monto > 0', name='check_income_monto_positivo'),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income_logs')
    op.drop_index(op.f('ix_smart_score_history_mes'), table_name='smart_score_history')
    op.drop_index(op.f('ix_smart_score_history_anio'), table_name='smart_score_history')
    op.drop_table('smart_score_history')
    op.drop_index(op.f('ix_goals_estado'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_expenses_fecha'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_categoria'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_budgets_mes'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_anio'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_alerts_tipo'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_leida'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
